version: "3.9"

services:
  slp-core:
    build: .
    image: slp-core:latest
    container_name: slp-core
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    working_dir: /app


